version: '3'

services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./database:/data/db

  # TODO: disable mongo-express in prod.
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGOEXPRESS_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGOEXPRESS_PASSWORD}"